"""
reno_service_data.py — the service and location taxonomy for Reno Rise.

Edit this file to add a service or a neighbourhood, then re-run
make_service_keywords.py. Nothing else needs to change.

Each service: (slug, display name, search term, category, core?)
  search term = what people actually type. The slug is a URL, not a query.
  core = True  -> full geo treatment: every municipality AND every neighbourhood
  core = False -> head terms, regions, and the 16 biggest municipalities

Keep `core` tight. It is the multiplier that decides the size of the matrix,
and every core service implies real pages. Roughly 50 core services is the
sensible ceiling for one site.
"""

# ---------------------------------------------------------------------------
# SERVICES — 25 categories, trade-level depth in each
# ---------------------------------------------------------------------------
SERVICES = [
    # ===== KITCHEN =========================================================
    ("kitchen-renovation", "Kitchen Renovation", "kitchen renovation", "Kitchen", True),
    ("kitchen-remodeling", "Kitchen Remodeling", "kitchen remodeling", "Kitchen", True),
    ("custom-kitchen-cabinets", "Custom Kitchen Cabinets", "custom kitchen cabinets", "Kitchen", True),
    ("kitchen-cabinet-installation", "Kitchen Cabinet Installation", "kitchen cabinet installation", "Kitchen", False),
    ("kitchen-cabinet-refacing", "Kitchen Cabinet Refacing", "kitchen cabinet refacing", "Kitchen", False),
    ("kitchen-cabinet-painting", "Kitchen Cabinet Painting", "kitchen cabinet painting", "Kitchen", False),
    ("kitchen-island-installation", "Kitchen Island Installation", "kitchen island installation", "Kitchen", False),
    ("countertop-installation", "Countertop Installation", "countertop installation", "Kitchen", True),
    ("quartz-countertop-installation", "Quartz Countertop Installation", "quartz countertop installation", "Kitchen", False),
    ("granite-countertop-installation", "Granite Countertop Installation", "granite countertop installation", "Kitchen", False),
    ("butcher-block-countertop", "Butcher Block Countertop", "butcher block countertop installation", "Kitchen", False),
    ("backsplash-installation", "Backsplash Installation", "backsplash installation", "Kitchen", False),
    ("kitchen-sink-installation", "Kitchen Sink Installation", "kitchen sink installation", "Kitchen", False),
    ("range-hood-installation", "Range Hood Installation", "range hood installation", "Kitchen", False),
    ("pantry-installation", "Pantry Installation", "pantry installation", "Kitchen", False),
    ("small-kitchen-renovation", "Small Kitchen Renovation", "small kitchen renovation", "Kitchen", False),
    ("condo-kitchen-renovation", "Condo Kitchen Renovation", "condo kitchen renovation", "Kitchen", False),
    ("galley-kitchen-renovation", "Galley Kitchen Renovation", "galley kitchen renovation", "Kitchen", False),

    # ===== BATHROOM ========================================================
    ("bathroom-renovation", "Bathroom Renovation", "bathroom renovation", "Bathroom", True),
    ("bathroom-remodeling", "Bathroom Remodeling", "bathroom remodeling", "Bathroom", True),
    ("small-bathroom-renovation", "Small Bathroom Renovation", "small bathroom renovation", "Bathroom", False),
    ("ensuite-renovation", "Ensuite Renovation", "ensuite renovation", "Bathroom", False),
    ("powder-room-renovation", "Powder Room Renovation", "powder room renovation", "Bathroom", False),
    ("basement-bathroom-installation", "Basement Bathroom Installation", "basement bathroom installation", "Bathroom", False),
    ("shower-installation", "Shower Installation", "shower installation", "Bathroom", True),
    ("walk-in-shower-installation", "Walk-In Shower Installation", "walk in shower installation", "Bathroom", False),
    ("curbless-shower-installation", "Curbless Shower Installation", "curbless shower installation", "Bathroom", False),
    ("bathtub-to-shower-conversion", "Bathtub to Shower Conversion", "bathtub to shower conversion", "Bathroom", False),
    ("bathtub-installation", "Bathtub Installation", "bathtub installation", "Bathroom", False),
    ("bathroom-vanity-installation", "Bathroom Vanity Installation", "bathroom vanity installation", "Bathroom", False),
    ("bathroom-waterproofing", "Bathroom Waterproofing", "bathroom waterproofing", "Bathroom", False),
    ("bathroom-tile-installation", "Bathroom Tile Installation", "bathroom tile installation", "Bathroom", False),
    ("shower-glass-installation", "Shower Glass Installation", "shower glass installation", "Bathroom", False),
    ("toilet-installation", "Toilet Installation", "toilet installation", "Bathroom", False),
    ("bathroom-exhaust-fan-installation", "Bathroom Exhaust Fan Installation", "bathroom exhaust fan installation", "Bathroom", False),
    ("accessible-bathroom-renovation", "Accessible Bathroom Renovation", "accessible bathroom renovation", "Bathroom", False),

    # ===== BASEMENT ========================================================
    ("basement-renovation", "Basement Renovation", "basement renovation", "Basement", True),
    ("basement-finishing", "Basement Finishing", "basement finishing", "Basement", True),
    ("legal-basement-apartment", "Legal Basement Apartment", "legal basement apartment", "Basement", True),
    ("basement-apartment-construction", "Basement Apartment Construction", "basement apartment construction", "Basement", False),
    ("secondary-suite-construction", "Secondary Suite Construction", "secondary suite construction", "Basement", False),
    ("in-law-suite-construction", "In-Law Suite Construction", "in law suite construction", "Basement", False),
    ("basement-underpinning", "Basement Underpinning", "basement underpinning", "Basement", False),
    ("basement-lowering", "Basement Lowering", "basement lowering", "Basement", False),
    ("bench-footing", "Bench Footing", "bench footing basement", "Basement", False),
    ("egress-window-installation", "Egress Window Installation", "egress window installation", "Basement", False),
    ("walkout-basement-construction", "Walkout Basement Construction", "walkout basement construction", "Basement", False),
    ("basement-framing", "Basement Framing", "basement framing", "Basement", False),
    ("basement-kitchen-installation", "Basement Kitchen Installation", "basement kitchen installation", "Basement", False),
    ("basement-soundproofing", "Basement Soundproofing", "basement soundproofing", "Basement", False),
    ("basement-ceiling-installation", "Basement Ceiling Installation", "basement ceiling installation", "Basement", False),
    ("crawl-space-conversion", "Crawl Space Conversion", "crawl space conversion", "Basement", False),

    # ===== FLOORING ========================================================
    ("flooring-installation", "Flooring Installation", "flooring installation", "Flooring", True),
    ("flooring-contractor", "Flooring Contractor", "flooring contractor", "Flooring", True),
    ("flooring-replacement", "Flooring Replacement", "flooring replacement", "Flooring", True),
    ("hardwood-floor-installation", "Hardwood Floor Installation", "hardwood floor installation", "Flooring", True),
    ("engineered-hardwood-installation", "Engineered Hardwood Installation", "engineered hardwood installation", "Flooring", False),
    ("laminate-floor-installation", "Laminate Floor Installation", "laminate floor installation", "Flooring", True),
    ("vinyl-plank-installation", "Vinyl Plank Installation", "vinyl plank installation", "Flooring", True),
    ("tile-floor-installation", "Tile Floor Installation", "tile floor installation", "Flooring", True),
    ("carpet-installation", "Carpet Installation", "carpet installation", "Flooring", False),
    ("floor-leveling", "Floor Leveling", "floor leveling", "Flooring", False),
    ("subfloor-repair", "Subfloor Repair", "subfloor repair", "Flooring", False),
    ("subfloor-installation", "Subfloor Installation", "subfloor installation", "Flooring", False),
    ("floor-repair", "Floor Repair", "floor repair", "Flooring", False),
    ("hardwood-floor-refinishing", "Hardwood Floor Refinishing", "hardwood floor refinishing", "Flooring", False),
    ("hardwood-floor-sanding", "Hardwood Floor Sanding", "hardwood floor sanding", "Flooring", False),
    ("heated-floor-installation", "Heated Floor Installation", "heated floor installation", "Flooring", False),
    ("squeaky-floor-repair", "Squeaky Floor Repair", "squeaky floor repair", "Flooring", False),
    ("floor-transition-installation", "Floor Transition Installation", "floor transition installation", "Flooring", False),

    # ===== PAINTING ========================================================
    ("interior-painting", "Interior Painting", "interior painting", "Painting", True),
    ("exterior-painting", "Exterior Painting", "exterior painting", "Painting", True),
    ("house-painting", "House Painting", "house painting", "Painting", True),
    ("painting-contractor", "Painting Contractor", "painting contractor", "Painting", True),
    ("cabinet-painting", "Cabinet Painting", "cabinet painting", "Painting", False),
    ("ceiling-painting", "Ceiling Painting", "ceiling painting", "Painting", False),
    ("trim-painting", "Trim Painting", "trim painting", "Painting", False),
    ("door-painting", "Door Painting", "door painting", "Painting", False),
    ("condo-painting", "Condo Painting", "condo painting", "Painting", False),
    ("wallpaper-removal", "Wallpaper Removal", "wallpaper removal", "Painting", False),
    ("wallpaper-installation", "Wallpaper Installation", "wallpaper installation", "Painting", False),
    ("staircase-painting", "Staircase Painting", "staircase painting", "Painting", False),
    ("garage-painting", "Garage Painting", "garage painting", "Painting", False),
    ("stucco-painting", "Stucco Painting", "stucco painting", "Painting", False),
    ("brick-painting", "Brick Painting", "brick painting", "Painting", False),

    # ===== DOORS ===========================================================
    ("door-installation", "Door Installation", "door installation", "Doors", True),
    ("custom-doors", "Custom Doors", "custom doors", "Doors", True),
    ("door-replacement", "Door Replacement", "door replacement", "Doors", True),
    ("interior-door-installation", "Interior Door Installation", "interior door installation", "Doors", True),
    ("exterior-door-installation", "Exterior Door Installation", "exterior door installation", "Doors", True),
    ("front-door-installation", "Front Door Installation", "front door installation", "Doors", False),
    ("patio-door-installation", "Patio Door Installation", "patio door installation", "Doors", False),
    ("sliding-door-installation", "Sliding Door Installation", "sliding door installation", "Doors", False),
    ("french-door-installation", "French Door Installation", "french door installation", "Doors", False),
    ("barn-door-installation", "Barn Door Installation", "barn door installation", "Doors", False),
    ("pocket-door-installation", "Pocket Door Installation", "pocket door installation", "Doors", False),
    ("bifold-door-installation", "Bifold Door Installation", "bifold door installation", "Doors", False),
    ("closet-door-installation", "Closet Door Installation", "closet door installation", "Doors", False),
    ("storm-door-installation", "Storm Door Installation", "storm door installation", "Doors", False),
    ("garage-door-installation", "Garage Door Installation", "garage door installation", "Doors", False),
    ("door-frame-repair", "Door Frame Repair", "door frame repair", "Doors", False),
    ("door-hardware-installation", "Door Hardware Installation", "door hardware installation", "Doors", False),

    # ===== WINDOWS =========================================================
    ("window-installation", "Window Installation", "window installation", "Windows", True),
    ("window-replacement", "Window Replacement", "window replacement", "Windows", True),
    ("vinyl-window-installation", "Vinyl Window Installation", "vinyl window installation", "Windows", False),
    ("casement-window-installation", "Casement Window Installation", "casement window installation", "Windows", False),
    ("bay-window-installation", "Bay Window Installation", "bay window installation", "Windows", False),
    ("bow-window-installation", "Bow Window Installation", "bow window installation", "Windows", False),
    ("basement-window-replacement", "Basement Window Replacement", "basement window replacement", "Windows", False),
    ("skylight-installation", "Skylight Installation", "skylight installation", "Windows", False),
    ("window-trim-installation", "Window Trim Installation", "window trim installation", "Windows", False),
    ("window-sill-replacement", "Window Sill Replacement", "window sill replacement", "Windows", False),
    ("window-repair", "Window Repair", "window repair", "Windows", False),
    ("window-glass-replacement", "Window Glass Replacement", "window glass replacement", "Windows", False),

    # ===== DECKS ===========================================================
    ("deck-building", "Deck Building", "deck building", "Decks", True),
    ("deck-builder", "Deck Builder", "deck builder", "Decks", True),
    ("deck-repair", "Deck Repair", "deck repair", "Decks", True),
    ("deck-replacement", "Deck Replacement", "deck replacement", "Decks", False),
    ("composite-deck-installation", "Composite Deck Installation", "composite deck installation", "Decks", False),
    ("wood-deck-building", "Wood Deck Building", "wood deck building", "Decks", False),
    ("cedar-deck-building", "Cedar Deck Building", "cedar deck building", "Decks", False),
    ("multi-level-deck-building", "Multi-Level Deck Building", "multi level deck building", "Decks", False),
    ("deck-staining", "Deck Staining", "deck staining", "Decks", False),
    ("deck-railing-installation", "Deck Railing Installation", "deck railing installation", "Decks", False),
    ("deck-stairs-construction", "Deck Stairs Construction", "deck stairs construction", "Decks", False),
    ("pergola-building", "Pergola Building", "pergola building", "Decks", False),
    ("gazebo-building", "Gazebo Building", "gazebo building", "Decks", False),
    ("porch-building", "Porch Building", "porch building", "Decks", False),

    # ===== FENCES ==========================================================
    ("fence-installation", "Fence Installation", "fence installation", "Fences", True),
    ("fence-contractor", "Fence Contractor", "fence contractor", "Fences", True),
    ("fence-repair", "Fence Repair", "fence repair", "Fences", True),
    ("fence-replacement", "Fence Replacement", "fence replacement", "Fences", False),
    ("wood-fence-installation", "Wood Fence Installation", "wood fence installation", "Fences", False),
    ("cedar-fence-installation", "Cedar Fence Installation", "cedar fence installation", "Fences", False),
    ("vinyl-fence-installation", "Vinyl Fence Installation", "vinyl fence installation", "Fences", False),
    ("privacy-fence-installation", "Privacy Fence Installation", "privacy fence installation", "Fences", False),
    ("chain-link-fence-installation", "Chain Link Fence Installation", "chain link fence installation", "Fences", False),
    ("aluminum-fence-installation", "Aluminum Fence Installation", "aluminum fence installation", "Fences", False),
    ("composite-fence-installation", "Composite Fence Installation", "composite fence installation", "Fences", False),
    ("gate-installation", "Gate Installation", "gate installation", "Fences", False),
    ("fence-post-replacement", "Fence Post Replacement", "fence post replacement", "Fences", False),
    ("fence-staining", "Fence Staining", "fence staining", "Fences", False),

    # ===== DRYWALL & CEILINGS ==============================================
    ("drywall-installation", "Drywall Installation", "drywall installation", "Drywall & Ceilings", True),
    ("drywall-repair", "Drywall Repair", "drywall repair", "Drywall & Ceilings", True),
    ("drywall-contractor", "Drywall Contractor", "drywall contractor", "Drywall & Ceilings", True),
    ("drywall-taping", "Drywall Taping", "drywall taping", "Drywall & Ceilings", False),
    ("drywall-mudding", "Drywall Mudding", "drywall mudding", "Drywall & Ceilings", False),
    ("ceiling-repair", "Ceiling Repair", "ceiling repair", "Drywall & Ceilings", False),
    ("ceiling-installation", "Ceiling Installation", "ceiling installation", "Drywall & Ceilings", False),
    ("popcorn-ceiling-removal", "Popcorn Ceiling Removal", "popcorn ceiling removal", "Drywall & Ceilings", False),
    ("coffered-ceiling-installation", "Coffered Ceiling Installation", "coffered ceiling installation", "Drywall & Ceilings", False),
    ("water-damage-drywall-repair", "Water Damage Drywall Repair", "water damage drywall repair", "Drywall & Ceilings", False),
    ("plaster-repair", "Plaster Repair", "plaster repair", "Drywall & Ceilings", False),
    ("soundproof-drywall-installation", "Soundproof Drywall Installation", "soundproof drywall installation", "Drywall & Ceilings", False),
    ("drop-ceiling-installation", "Drop Ceiling Installation", "drop ceiling installation", "Drywall & Ceilings", False),

    # ===== TRIM & MILLWORK =================================================
    ("trim-carpentry", "Trim Carpentry", "trim carpentry", "Trim & Millwork", True),
    ("baseboard-installation", "Baseboard Installation", "baseboard installation", "Trim & Millwork", True),
    ("crown-moulding-installation", "Crown Moulding Installation", "crown moulding installation", "Trim & Millwork", True),
    ("casing-installation", "Casing Installation", "door casing installation", "Trim & Millwork", False),
    ("wainscoting-installation", "Wainscoting Installation", "wainscoting installation", "Trim & Millwork", False),
    ("panel-moulding-installation", "Panel Moulding Installation", "panel moulding installation", "Trim & Millwork", False),
    ("shiplap-installation", "Shiplap Installation", "shiplap installation", "Trim & Millwork", False),
    ("chair-rail-installation", "Chair Rail Installation", "chair rail installation", "Trim & Millwork", False),
    ("window-casing-installation", "Window Casing Installation", "window casing installation", "Trim & Millwork", False),
    ("interior-trim-replacement", "Interior Trim Replacement", "interior trim replacement", "Trim & Millwork", False),
    ("custom-millwork", "Custom Millwork", "custom millwork", "Trim & Millwork", False),

    # ===== TILE ============================================================
    ("tile-installation", "Tile Installation", "tile installation", "Tile", True),
    ("tile-contractor", "Tile Contractor", "tile contractor", "Tile", True),
    ("kitchen-tile-installation", "Kitchen Tile Installation", "kitchen tile installation", "Tile", False),
    ("shower-tile-installation", "Shower Tile Installation", "shower tile installation", "Tile", False),
    ("porcelain-tile-installation", "Porcelain Tile Installation", "porcelain tile installation", "Tile", False),
    ("marble-tile-installation", "Marble Tile Installation", "marble tile installation", "Tile", False),
    ("mosaic-tile-installation", "Mosaic Tile Installation", "mosaic tile installation", "Tile", False),
    ("large-format-tile-installation", "Large Format Tile Installation", "large format tile installation", "Tile", False),
    ("heated-tile-installation", "Heated Tile Installation", "heated tile installation", "Tile", False),
    ("tile-repair", "Tile Repair", "tile repair", "Tile", False),
    ("regrouting", "Regrouting", "regrouting", "Tile", False),
    ("grout-repair", "Grout Repair", "grout repair", "Tile", False),
    ("tile-removal", "Tile Removal", "tile removal", "Tile", False),

    # ===== CABINETRY & STORAGE =============================================
    ("custom-cabinetry", "Custom Cabinetry", "custom cabinetry", "Cabinetry & Storage", True),
    ("built-in-shelving", "Built-In Shelving", "built in shelving", "Cabinetry & Storage", False),
    ("custom-closet-installation", "Custom Closet Installation", "custom closet installation", "Cabinetry & Storage", True),
    ("walk-in-closet-installation", "Walk-In Closet Installation", "walk in closet installation", "Cabinetry & Storage", False),
    ("closet-organizer-installation", "Closet Organizer Installation", "closet organizer installation", "Cabinetry & Storage", False),
    ("mudroom-built-ins", "Mudroom Built-Ins", "mudroom built in cabinets", "Cabinetry & Storage", False),
    ("entertainment-unit-installation", "Entertainment Unit Installation", "built in entertainment unit", "Cabinetry & Storage", False),
    ("bookshelf-installation", "Bookshelf Installation", "built in bookshelf installation", "Cabinetry & Storage", False),
    ("fireplace-surround-installation", "Fireplace Surround Installation", "fireplace surround installation", "Cabinetry & Storage", False),
    ("feature-wall-installation", "Feature Wall Installation", "feature wall installation", "Cabinetry & Storage", False),
    ("bar-cabinetry-installation", "Bar Cabinetry Installation", "wet bar installation", "Cabinetry & Storage", False),
    ("garage-storage-installation", "Garage Storage Installation", "garage storage installation", "Cabinetry & Storage", False),

    # ===== WHOLE HOME & STRUCTURAL =========================================
    ("home-renovation", "Home Renovation", "home renovation", "Whole Home", True),
    ("whole-home-renovation", "Whole Home Renovation", "whole home renovation", "Whole Home", True),
    ("general-contractor", "General Contractor", "general contractor", "Whole Home", True),
    ("renovation-contractor", "Renovation Contractor", "renovation contractor", "Whole Home", True),
    ("home-addition", "Home Addition", "home addition", "Whole Home", True),
    ("second-storey-addition", "Second Storey Addition", "second storey addition", "Whole Home", True),
    ("house-extension", "House Extension", "house extension", "Whole Home", True),
    ("rear-addition", "Rear Addition", "rear addition", "Whole Home", False),
    ("garage-conversion", "Garage Conversion", "garage conversion", "Whole Home", False),
    ("open-concept-renovation", "Open Concept Renovation", "open concept renovation", "Whole Home", False),
    ("load-bearing-wall-removal", "Load Bearing Wall Removal", "load bearing wall removal", "Whole Home", False),
    ("structural-beam-installation", "Structural Beam Installation", "structural beam installation", "Whole Home", False),
    ("condo-renovation", "Condo Renovation", "condo renovation", "Whole Home", True),
    ("interior-renovation", "Interior Renovation", "interior renovation", "Whole Home", True),
    ("exterior-renovation", "Exterior Renovation", "exterior renovation", "Whole Home", True),
    ("home-remodeling", "Home Remodeling", "home remodeling", "Whole Home", False),
    ("heritage-home-renovation", "Heritage Home Renovation", "heritage home renovation", "Whole Home", False),
    ("custom-home-building", "Custom Home Building", "custom home builder", "Whole Home", False),
    ("laneway-house-construction", "Laneway House Construction", "laneway house construction", "Whole Home", False),
    ("garden-suite-construction", "Garden Suite Construction", "garden suite construction", "Whole Home", False),

    # ===== EXTERIOR & SIDING ===============================================
    ("siding-installation", "Siding Installation", "siding installation", "Exterior & Siding", True),
    ("siding-replacement", "Siding Replacement", "siding replacement", "Exterior & Siding", False),
    ("siding-repair", "Siding Repair", "siding repair", "Exterior & Siding", False),
    ("vinyl-siding-installation", "Vinyl Siding Installation", "vinyl siding installation", "Exterior & Siding", False),
    ("fibre-cement-siding-installation", "Fibre Cement Siding Installation", "fibre cement siding installation", "Exterior & Siding", False),
    ("stone-veneer-installation", "Stone Veneer Installation", "stone veneer installation", "Exterior & Siding", False),
    ("stucco-installation", "Stucco Installation", "stucco installation", "Exterior & Siding", False),
    ("stucco-repair", "Stucco Repair", "stucco repair", "Exterior & Siding", False),
    ("soffit-and-fascia-installation", "Soffit and Fascia Installation", "soffit and fascia installation", "Exterior & Siding", False),
    ("eavestrough-installation", "Eavestrough Installation", "eavestrough installation", "Exterior & Siding", False),
    ("porch-renovation", "Porch Renovation", "porch renovation", "Exterior & Siding", False),
    ("front-steps-replacement", "Front Steps Replacement", "front steps replacement", "Exterior & Siding", False),
    ("exterior-trim-replacement", "Exterior Trim Replacement", "exterior trim replacement", "Exterior & Siding", False),
    ("curb-appeal-renovation", "Curb Appeal Renovation", "curb appeal renovation", "Exterior & Siding", False),

    # ===== STAIRS & RAILINGS ===============================================
    ("staircase-renovation", "Staircase Renovation", "staircase renovation", "Stairs & Railings", True),
    ("stair-installation", "Stair Installation", "stair installation", "Stairs & Railings", False),
    ("stair-railing-installation", "Stair Railing Installation", "stair railing installation", "Stairs & Railings", False),
    ("glass-railing-installation", "Glass Railing Installation", "glass railing installation", "Stairs & Railings", False),
    ("iron-railing-installation", "Iron Railing Installation", "iron railing installation", "Stairs & Railings", False),
    ("stair-refinishing", "Stair Refinishing", "stair refinishing", "Stairs & Railings", False),
    ("stair-tread-replacement", "Stair Tread Replacement", "stair tread replacement", "Stairs & Railings", False),
    ("carpet-to-hardwood-stairs", "Carpet to Hardwood Stairs", "carpet to hardwood stairs", "Stairs & Railings", False),
    ("floating-staircase-installation", "Floating Staircase Installation", "floating staircase installation", "Stairs & Railings", False),
    ("basement-stair-replacement", "Basement Stair Replacement", "basement stair replacement", "Stairs & Railings", False),

    # ===== SPECIALTY ROOMS =================================================
    ("laundry-room-renovation", "Laundry Room Renovation", "laundry room renovation", "Specialty Rooms", False),
    ("garage-renovation", "Garage Renovation", "garage renovation", "Specialty Rooms", False),
    ("closet-renovation", "Closet Renovation", "closet renovation", "Specialty Rooms", False),
    ("home-office-renovation", "Home Office Renovation", "home office renovation", "Specialty Rooms", False),
    ("attic-renovation", "Attic Renovation", "attic renovation", "Specialty Rooms", False),
    ("sunroom-addition", "Sunroom Addition", "sunroom addition", "Specialty Rooms", False),
    ("mudroom-renovation", "Mudroom Renovation", "mudroom renovation", "Specialty Rooms", False),
    ("home-gym-construction", "Home Gym Construction", "home gym construction", "Specialty Rooms", False),
    ("home-theatre-construction", "Home Theatre Construction", "home theatre construction", "Specialty Rooms", False),
    ("nursery-renovation", "Nursery Renovation", "nursery renovation", "Specialty Rooms", False),
    ("wine-cellar-construction", "Wine Cellar Construction", "wine cellar construction", "Specialty Rooms", False),
    ("pantry-renovation", "Pantry Renovation", "pantry renovation", "Specialty Rooms", False),

    # ===== CONCRETE & MASONRY ==============================================
    ("concrete-contractor", "Concrete Contractor", "concrete contractor", "Concrete & Masonry", True),
    ("concrete-driveway-installation", "Concrete Driveway Installation", "concrete driveway installation", "Concrete & Masonry", False),
    ("concrete-walkway-installation", "Concrete Walkway Installation", "concrete walkway installation", "Concrete & Masonry", False),
    ("concrete-patio-installation", "Concrete Patio Installation", "concrete patio installation", "Concrete & Masonry", False),
    ("concrete-steps-replacement", "Concrete Steps Replacement", "concrete steps replacement", "Concrete & Masonry", False),
    ("concrete-repair", "Concrete Repair", "concrete repair", "Concrete & Masonry", False),
    ("interlocking-installation", "Interlocking Installation", "interlocking installation", "Concrete & Masonry", True),
    ("retaining-wall-construction", "Retaining Wall Construction", "retaining wall construction", "Concrete & Masonry", False),
    ("brick-repair", "Brick Repair", "brick repair", "Concrete & Masonry", False),
    ("brick-repointing", "Brick Repointing", "brick repointing", "Concrete & Masonry", False),
    ("parging", "Parging", "parging", "Concrete & Masonry", False),
    ("chimney-repair", "Chimney Repair", "chimney repair", "Concrete & Masonry", False),
    ("masonry-contractor", "Masonry Contractor", "masonry contractor", "Concrete & Masonry", False),
    ("foundation-repair", "Foundation Repair", "foundation repair", "Concrete & Masonry", True),
    ("foundation-crack-repair", "Foundation Crack Repair", "foundation crack repair", "Concrete & Masonry", False),

    # ===== WATERPROOFING & DRAINAGE ========================================
    ("basement-waterproofing", "Basement Waterproofing", "basement waterproofing", "Waterproofing", True),
    ("waterproofing-contractor", "Waterproofing Contractor", "waterproofing contractor", "Waterproofing", True),
    ("interior-waterproofing", "Interior Waterproofing", "interior basement waterproofing", "Waterproofing", False),
    ("exterior-waterproofing", "Exterior Waterproofing", "exterior basement waterproofing", "Waterproofing", False),
    ("weeping-tile-installation", "Weeping Tile Installation", "weeping tile installation", "Waterproofing", False),
    ("french-drain-installation", "French Drain Installation", "french drain installation", "Waterproofing", False),
    ("sump-pump-installation", "Sump Pump Installation", "sump pump installation", "Waterproofing", False),
    ("backwater-valve-installation", "Backwater Valve Installation", "backwater valve installation", "Waterproofing", False),
    ("window-well-installation", "Window Well Installation", "window well installation", "Waterproofing", False),
    ("wet-basement-repair", "Wet Basement Repair", "wet basement repair", "Waterproofing", False),
    ("crawl-space-waterproofing", "Crawl Space Waterproofing", "crawl space waterproofing", "Waterproofing", False),
    ("mould-remediation", "Mould Remediation", "mould remediation", "Waterproofing", False),

    # ===== ELECTRICAL ======================================================
    ("electrical-contractor", "Electrical Contractor", "electrical contractor", "Electrical", True),
    ("electrical-panel-upgrade", "Electrical Panel Upgrade", "electrical panel upgrade", "Electrical", True),
    ("house-rewiring", "House Rewiring", "house rewiring", "Electrical", False),
    ("knob-and-tube-removal", "Knob and Tube Removal", "knob and tube removal", "Electrical", False),
    ("aluminum-wiring-replacement", "Aluminum Wiring Replacement", "aluminum wiring replacement", "Electrical", False),
    ("pot-light-installation", "Pot Light Installation", "pot light installation", "Electrical", True),
    ("light-fixture-installation", "Light Fixture Installation", "light fixture installation", "Electrical", False),
    ("under-cabinet-lighting-installation", "Under Cabinet Lighting", "under cabinet lighting installation", "Electrical", False),
    ("ev-charger-installation", "EV Charger Installation", "ev charger installation", "Electrical", False),
    ("outlet-installation", "Outlet Installation", "outlet installation", "Electrical", False),
    ("ceiling-fan-installation", "Ceiling Fan Installation", "ceiling fan installation", "Electrical", False),
    ("basement-electrical-rough-in", "Basement Electrical Rough-In", "basement electrical rough in", "Electrical", False),
    ("smart-home-wiring", "Smart Home Wiring", "smart home wiring", "Electrical", False),

    # ===== PLUMBING ========================================================
    ("plumbing-contractor", "Plumbing Contractor", "plumbing contractor", "Plumbing", True),
    ("plumbing-rough-in", "Plumbing Rough-In", "plumbing rough in", "Plumbing", False),
    ("repiping", "Repiping", "house repiping", "Plumbing", False),
    ("galvanised-pipe-replacement", "Galvanised Pipe Replacement", "galvanized pipe replacement", "Plumbing", False),
    ("drain-relocation", "Drain Relocation", "drain relocation", "Plumbing", False),
    ("water-line-replacement", "Water Line Replacement", "water line replacement", "Plumbing", False),
    ("bathroom-plumbing-installation", "Bathroom Plumbing Installation", "bathroom plumbing installation", "Plumbing", False),
    ("kitchen-plumbing-installation", "Kitchen Plumbing Installation", "kitchen plumbing installation", "Plumbing", False),
    ("laundry-hookup-installation", "Laundry Hookup Installation", "laundry hookup installation", "Plumbing", False),
    ("water-heater-installation", "Water Heater Installation", "water heater installation", "Plumbing", False),

    # ===== INSULATION & ENERGY =============================================
    ("insulation-contractor", "Insulation Contractor", "insulation contractor", "Insulation & Energy", True),
    ("attic-insulation", "Attic Insulation", "attic insulation", "Insulation & Energy", True),
    ("spray-foam-insulation", "Spray Foam Insulation", "spray foam insulation", "Insulation & Energy", False),
    ("blown-in-insulation", "Blown-In Insulation", "blown in insulation", "Insulation & Energy", False),
    ("basement-insulation", "Basement Insulation", "basement insulation", "Insulation & Energy", False),
    ("wall-insulation", "Wall Insulation", "wall insulation", "Insulation & Energy", False),
    ("air-sealing", "Air Sealing", "air sealing home", "Insulation & Energy", False),
    ("vapour-barrier-installation", "Vapour Barrier Installation", "vapour barrier installation", "Insulation & Energy", False),
    ("soundproofing-installation", "Soundproofing Installation", "soundproofing installation", "Insulation & Energy", False),

    # ===== ROOFING =========================================================
    ("roofing-contractor", "Roofing Contractor", "roofing contractor", "Roofing", True),
    ("roof-replacement", "Roof Replacement", "roof replacement", "Roofing", True),
    ("shingle-replacement", "Shingle Replacement", "shingle replacement", "Roofing", False),
    ("flat-roof-installation", "Flat Roof Installation", "flat roof installation", "Roofing", False),
    ("metal-roof-installation", "Metal Roof Installation", "metal roof installation", "Roofing", False),
    ("roof-repair", "Roof Repair", "roof repair", "Roofing", False),
    ("roof-leak-repair", "Roof Leak Repair", "roof leak repair", "Roofing", False),
    ("roof-ventilation-installation", "Roof Ventilation Installation", "roof ventilation installation", "Roofing", False),
    ("dormer-construction", "Dormer Construction", "dormer construction", "Roofing", False),

    # ===== ACCESSIBILITY ===================================================
    ("accessibility-renovation", "Accessibility Renovation", "accessibility renovation", "Accessibility", False),
    ("aging-in-place-renovation", "Aging in Place Renovation", "aging in place renovation", "Accessibility", False),
    ("wheelchair-ramp-installation", "Wheelchair Ramp Installation", "wheelchair ramp installation", "Accessibility", False),
    ("grab-bar-installation", "Grab Bar Installation", "grab bar installation", "Accessibility", False),
    ("barrier-free-shower-installation", "Barrier-Free Shower Installation", "barrier free shower installation", "Accessibility", False),
    ("doorway-widening", "Doorway Widening", "doorway widening", "Accessibility", False),
    ("stair-lift-installation", "Stair Lift Installation", "stair lift installation", "Accessibility", False),

    # ===== DEMOLITION & PREP ===============================================
    ("interior-demolition", "Interior Demolition", "interior demolition", "Demolition & Prep", False),
    ("demolition-contractor", "Demolition Contractor", "demolition contractor", "Demolition & Prep", False),
    ("kitchen-demolition", "Kitchen Demolition", "kitchen demolition", "Demolition & Prep", False),
    ("bathroom-demolition", "Bathroom Demolition", "bathroom demolition", "Demolition & Prep", False),
    ("basement-demolition", "Basement Demolition", "basement demolition", "Demolition & Prep", False),
    ("renovation-junk-removal", "Renovation Junk Removal", "renovation junk removal", "Demolition & Prep", False),
    ("asbestos-removal", "Asbestos Removal", "asbestos removal", "Demolition & Prep", False),
    ("site-cleanup", "Site Cleanup", "construction site cleanup", "Demolition & Prep", False),
]

# ---------------------------------------------------------------------------
# LOCATIONS
#
# tier "municipality" = a city or town. Core + secondary service coverage.
# tier "micro"        = a neighbourhood or community. Core services only.
# ---------------------------------------------------------------------------
REGIONS = [
    ("toronto", "Toronto"),
    ("peel-region", "Peel Region"),
    ("york-region", "York Region"),
    ("durham-region", "Durham Region"),
    ("halton-region", "Halton Region"),
]

# (slug, name, region slug, tier, parent municipality name or "")
LOCATIONS = [
    # ===================== TORONTO =========================================
    ("toronto", "Toronto", "toronto", "municipality", ""),
    ("downtown-toronto", "Downtown Toronto", "toronto", "municipality", ""),
    ("north-york", "North York", "toronto", "municipality", ""),
    ("scarborough", "Scarborough", "toronto", "municipality", ""),
    ("etobicoke", "Etobicoke", "toronto", "municipality", ""),
    ("york", "York", "toronto", "municipality", ""),
    ("east-york", "East York", "toronto", "municipality", ""),

    ("leaside", "Leaside", "toronto", "micro", "East York"),
    ("the-beaches", "The Beaches", "toronto", "micro", "Toronto"),
    ("riverdale", "Riverdale", "toronto", "micro", "Toronto"),
    ("leslieville", "Leslieville", "toronto", "micro", "Toronto"),
    ("danforth", "Danforth", "toronto", "micro", "Toronto"),
    ("high-park", "High Park", "toronto", "micro", "Toronto"),
    ("the-junction", "The Junction", "toronto", "micro", "Toronto"),
    ("roncesvalles", "Roncesvalles", "toronto", "micro", "Toronto"),
    ("bloor-west-village", "Bloor West Village", "toronto", "micro", "Toronto"),
    ("swansea", "Swansea", "toronto", "micro", "Toronto"),
    ("parkdale", "Parkdale", "toronto", "micro", "Toronto"),
    ("liberty-village", "Liberty Village", "toronto", "micro", "Toronto"),
    ("king-west", "King West", "toronto", "micro", "Toronto"),
    ("queen-west", "Queen West", "toronto", "micro", "Toronto"),
    ("the-annex", "The Annex", "toronto", "micro", "Toronto"),
    ("yorkville", "Yorkville", "toronto", "micro", "Toronto"),
    ("rosedale", "Rosedale", "toronto", "micro", "Toronto"),
    ("forest-hill", "Forest Hill", "toronto", "micro", "Toronto"),
    ("casa-loma", "Casa Loma", "toronto", "micro", "Toronto"),
    ("little-italy", "Little Italy", "toronto", "micro", "Toronto"),
    ("trinity-bellwoods", "Trinity Bellwoods", "toronto", "micro", "Toronto"),
    ("cabbagetown", "Cabbagetown", "toronto", "micro", "Toronto"),
    ("corktown", "Corktown", "toronto", "micro", "Toronto"),
    ("regent-park", "Regent Park", "toronto", "micro", "Toronto"),
    ("harbourfront", "Harbourfront", "toronto", "micro", "Toronto"),
    ("st-clair-west", "St Clair West", "toronto", "micro", "Toronto"),
    ("wychwood", "Wychwood", "toronto", "micro", "Toronto"),
    ("oakwood-village", "Oakwood Village", "toronto", "micro", "York"),
    ("davisville", "Davisville", "toronto", "micro", "Toronto"),
    ("yonge-and-eglinton", "Yonge and Eglinton", "toronto", "micro", "Toronto"),
    ("lawrence-park", "Lawrence Park", "toronto", "micro", "Toronto"),
    ("bedford-park", "Bedford Park", "toronto", "micro", "Toronto"),
    ("willowdale", "Willowdale", "toronto", "micro", "North York"),
    ("bayview-village", "Bayview Village", "toronto", "micro", "North York"),
    ("don-mills", "Don Mills", "toronto", "micro", "North York"),
    ("thorncliffe-park", "Thorncliffe Park", "toronto", "micro", "East York"),
    ("agincourt", "Agincourt", "toronto", "micro", "Scarborough"),
    ("malvern", "Malvern", "toronto", "micro", "Scarborough"),
    ("guildwood", "Guildwood", "toronto", "micro", "Scarborough"),
    ("west-hill", "West Hill", "toronto", "micro", "Scarborough"),
    ("cliffside", "Cliffside", "toronto", "micro", "Scarborough"),
    ("woburn", "Woburn", "toronto", "micro", "Scarborough"),
    ("highland-creek", "Highland Creek", "toronto", "micro", "Scarborough"),
    ("mimico", "Mimico", "toronto", "micro", "Etobicoke"),
    ("long-branch", "Long Branch", "toronto", "micro", "Etobicoke"),
    ("new-toronto", "New Toronto", "toronto", "micro", "Etobicoke"),
    ("alderwood", "Alderwood", "toronto", "micro", "Etobicoke"),
    ("the-kingsway", "The Kingsway", "toronto", "micro", "Etobicoke"),
    ("islington", "Islington", "toronto", "micro", "Etobicoke"),
    ("humber-bay", "Humber Bay", "toronto", "micro", "Etobicoke"),
    ("weston", "Weston", "toronto", "micro", "York"),
    ("mount-dennis", "Mount Dennis", "toronto", "micro", "York"),

    # ===================== PEEL ============================================
    ("mississauga", "Mississauga", "peel-region", "municipality", ""),
    ("brampton", "Brampton", "peel-region", "municipality", ""),
    ("caledon", "Caledon", "peel-region", "municipality", ""),
    ("port-credit", "Port Credit", "peel-region", "micro", "Mississauga"),
    ("lorne-park", "Lorne Park", "peel-region", "micro", "Mississauga"),
    ("streetsville", "Streetsville", "peel-region", "micro", "Mississauga"),
    ("meadowvale", "Meadowvale", "peel-region", "micro", "Mississauga"),
    ("erin-mills", "Erin Mills", "peel-region", "micro", "Mississauga"),
    ("clarkson", "Clarkson", "peel-region", "micro", "Mississauga"),
    ("cooksville", "Cooksville", "peel-region", "micro", "Mississauga"),
    ("malton", "Malton", "peel-region", "micro", "Mississauga"),
    ("churchill-meadows", "Churchill Meadows", "peel-region", "micro", "Mississauga"),
    ("applewood", "Applewood", "peel-region", "micro", "Mississauga"),
    ("lakeview", "Lakeview", "peel-region", "micro", "Mississauga"),
    ("mineola", "Mineola", "peel-region", "micro", "Mississauga"),
    ("bramalea", "Bramalea", "peel-region", "micro", "Brampton"),
    ("heart-lake", "Heart Lake", "peel-region", "micro", "Brampton"),
    ("springdale", "Springdale", "peel-region", "micro", "Brampton"),
    ("castlemore", "Castlemore", "peel-region", "micro", "Brampton"),
    ("mount-pleasant", "Mount Pleasant", "peel-region", "micro", "Brampton"),
    ("fletchers-meadow", "Fletchers Meadow", "peel-region", "micro", "Brampton"),
    ("credit-valley", "Credit Valley", "peel-region", "micro", "Brampton"),
    ("bolton", "Bolton", "peel-region", "micro", "Caledon"),
    ("caledon-east", "Caledon East", "peel-region", "micro", "Caledon"),
    ("inglewood", "Inglewood", "peel-region", "micro", "Caledon"),

    # ===================== YORK ============================================
    ("markham", "Markham", "york-region", "municipality", ""),
    ("vaughan", "Vaughan", "york-region", "municipality", ""),
    ("richmond-hill", "Richmond Hill", "york-region", "municipality", ""),
    ("newmarket", "Newmarket", "york-region", "municipality", ""),
    ("aurora", "Aurora", "york-region", "municipality", ""),
    ("king-city", "King City", "york-region", "municipality", ""),
    ("whitchurch-stouffville", "Whitchurch-Stouffville", "york-region", "municipality", ""),
    ("georgina", "Georgina", "york-region", "municipality", ""),
    ("east-gwillimbury", "East Gwillimbury", "york-region", "municipality", ""),
    ("unionville", "Unionville", "york-region", "micro", "Markham"),
    ("thornhill", "Thornhill", "york-region", "micro", "Markham"),
    ("milliken", "Milliken", "york-region", "micro", "Markham"),
    ("cornell", "Cornell", "york-region", "micro", "Markham"),
    ("wismer", "Wismer", "york-region", "micro", "Markham"),
    ("berczy-village", "Berczy Village", "york-region", "micro", "Markham"),
    ("markham-village", "Markham Village", "york-region", "micro", "Markham"),
    ("woodbridge", "Woodbridge", "york-region", "micro", "Vaughan"),
    ("maple", "Maple", "york-region", "micro", "Vaughan"),
    ("kleinburg", "Kleinburg", "york-region", "micro", "Vaughan"),
    ("concord", "Concord", "york-region", "micro", "Vaughan"),
    ("patterson", "Patterson", "york-region", "micro", "Vaughan"),
    ("vellore-village", "Vellore Village", "york-region", "micro", "Vaughan"),
    ("oak-ridges", "Oak Ridges", "york-region", "micro", "Richmond Hill"),
    ("bayview-hill", "Bayview Hill", "york-region", "micro", "Richmond Hill"),
    ("mill-pond", "Mill Pond", "york-region", "micro", "Richmond Hill"),
    ("jefferson", "Jefferson", "york-region", "micro", "Richmond Hill"),
    ("nobleton", "Nobleton", "york-region", "micro", "King City"),
    ("schomberg", "Schomberg", "york-region", "micro", "King City"),
    ("stouffville", "Stouffville", "york-region", "micro", "Whitchurch-Stouffville"),
    ("keswick", "Keswick", "york-region", "micro", "Georgina"),
    ("sutton", "Sutton", "york-region", "micro", "Georgina"),
    ("jacksons-point", "Jacksons Point", "york-region", "micro", "Georgina"),
    ("holland-landing", "Holland Landing", "york-region", "micro", "East Gwillimbury"),
    ("sharon", "Sharon", "york-region", "micro", "East Gwillimbury"),
    ("mount-albert", "Mount Albert", "york-region", "micro", "East Gwillimbury"),

    # ===================== DURHAM ==========================================
    ("ajax", "Ajax", "durham-region", "municipality", ""),
    ("pickering", "Pickering", "durham-region", "municipality", ""),
    ("whitby", "Whitby", "durham-region", "municipality", ""),
    ("oshawa", "Oshawa", "durham-region", "municipality", ""),
    ("clarington", "Clarington", "durham-region", "municipality", ""),
    ("uxbridge", "Uxbridge", "durham-region", "municipality", ""),
    ("scugog", "Scugog", "durham-region", "municipality", ""),
    ("brock", "Brock", "durham-region", "municipality", ""),
    ("pickering-village", "Pickering Village", "durham-region", "micro", "Ajax"),
    ("westney-heights", "Westney Heights", "durham-region", "micro", "Ajax"),
    ("bay-ridges", "Bay Ridges", "durham-region", "micro", "Pickering"),
    ("rougemount", "Rougemount", "durham-region", "micro", "Pickering"),
    ("seaton", "Seaton", "durham-region", "micro", "Pickering"),
    ("brooklin", "Brooklin", "durham-region", "micro", "Whitby"),
    ("port-whitby", "Port Whitby", "durham-region", "micro", "Whitby"),
    ("taunton", "Taunton", "durham-region", "micro", "Oshawa"),
    ("windfields", "Windfields", "durham-region", "micro", "Oshawa"),
    ("bowmanville", "Bowmanville", "durham-region", "micro", "Clarington"),
    ("courtice", "Courtice", "durham-region", "micro", "Clarington"),
    ("newcastle", "Newcastle", "durham-region", "micro", "Clarington"),
    ("orono", "Orono", "durham-region", "micro", "Clarington"),
    ("port-perry", "Port Perry", "durham-region", "micro", "Scugog"),
    ("beaverton", "Beaverton", "durham-region", "micro", "Brock"),
    ("cannington", "Cannington", "durham-region", "micro", "Brock"),
    ("sunderland", "Sunderland", "durham-region", "micro", "Brock"),

    # ===================== HALTON ==========================================
    ("oakville", "Oakville", "halton-region", "municipality", ""),
    ("burlington", "Burlington", "halton-region", "municipality", ""),
    ("milton", "Milton", "halton-region", "municipality", ""),
    ("halton-hills", "Halton Hills", "halton-region", "municipality", ""),
    ("bronte", "Bronte", "halton-region", "micro", "Oakville"),
    ("glen-abbey", "Glen Abbey", "halton-region", "micro", "Oakville"),
    ("old-oakville", "Old Oakville", "halton-region", "micro", "Oakville"),
    ("joshua-creek", "Joshua Creek", "halton-region", "micro", "Oakville"),
    ("river-oaks", "River Oaks", "halton-region", "micro", "Oakville"),
    ("clearview", "Clearview", "halton-region", "micro", "Oakville"),
    ("aldershot", "Aldershot", "halton-region", "micro", "Burlington"),
    ("roseland", "Roseland", "halton-region", "micro", "Burlington"),
    ("millcroft", "Millcroft", "halton-region", "micro", "Burlington"),
    ("alton-village", "Alton Village", "halton-region", "micro", "Burlington"),
    ("tyandaga", "Tyandaga", "halton-region", "micro", "Burlington"),
    ("old-milton", "Old Milton", "halton-region", "micro", "Milton"),
    ("hawthorne-village", "Hawthorne Village", "halton-region", "micro", "Milton"),
    ("beaty", "Beaty", "halton-region", "micro", "Milton"),
    ("georgetown", "Georgetown", "halton-region", "micro", "Halton Hills"),
    ("acton", "Acton", "halton-region", "micro", "Halton Hills"),
]

# The municipalities that get coverage for every service, core or not.
MAJOR = [
    "toronto", "north-york", "scarborough", "etobicoke", "mississauga",
    "brampton", "markham", "vaughan", "richmond-hill", "oakville",
    "burlington", "whitby", "oshawa", "ajax", "pickering", "milton",
]
